import { useState } from 'react';
import {
  ArrowRight, Check, ChevronLeft, CircleHelp, Download,
  Globe2, LockKeyhole, Menu, Plane, Shield, Sparkles,
  UserRound, Utensils, X
} from 'lucide-react';

type Page = 'home' | 'about' | 'services' | 'fleet' | 'destinations' | 'dining' | 'concierge' | 'contact' | 'booking' | 'manage' | 'checkin' | 'status';
type BookingStep = 'search' | 'results' | 'seat' | 'dining' | 'passenger' | 'review' | 'confirmed';

const heroImage = 'https://images.pexels.com/photos/10362464/pexels-photo-10362464.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const images = {
  architecture: 'https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg?auto=compress&cs=tinysrgb&w=1200',
  cabin: 'https://images.pexels.com/photos/261946/pexels-photo-261946.jpeg?auto=compress&cs=tinysrgb&w=1200',
  dining: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=1200',
  paris: 'https://images.pexels.com/photos/532826/pexels-photo-532826.jpeg?auto=compress&cs=tinysrgb&w=900',
  london: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg?auto=compress&cs=tinysrgb&w=900',
  tokyo: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=900',
  dubai: 'https://images.pexels.com/photos/2044434/pexels-photo-2044434.jpeg?auto=compress&cs=tinysrgb&w=900',
};

const navItems: { label: string; page: Page }[] = [
  { label: 'About', page: 'about' }, { label: 'Services', page: 'services' }, { label: 'Fleet', page: 'fleet' },
  { label: 'Destinations', page: 'destinations' }, { label: 'Dining', page: 'dining' },
];
const flights = [
  { number: 'GA 001', from: 'Paris', to: 'Tokyo', depart: '10:35', arrive: '06:20 +1', duration: '12h 45m', aircraft: 'Guardian G1', price: '€4,850', stops: 'Non-stop' },
  { number: 'GA 214', from: 'Paris', to: 'Tokyo', depart: '21:10', arrive: '18:05 +1', duration: '13h 55m', aircraft: 'Guardian G2', price: '€3,980', stops: 'Non-stop' },
  { number: 'GA 087', from: 'Paris', to: 'Tokyo', depart: '07:40', arrive: '06:15 +1', duration: '15h 35m', aircraft: 'Guardian G2', price: '€3,420', stops: '1 stop' },
];
const meals = [
  { name: 'Beef Tenderloin au Jus', category: 'Dinner', description: 'Premium beef tenderloin, pommes purée and a restrained red wine jus.', ingredients: 'Charolais beef · Ratte potato · Bordelaise jus', calories: '680 kcal', image: images.dining, pairing: 'Pauillac 2018' },
  { name: 'Truffle & Comté Omelette', category: 'Breakfast', description: 'French eggs, black truffle, aged Comté cheese and fine herbs.', ingredients: 'Eggs · Périgord truffle · Comté · Chives', calories: '420 kcal', image: images.cabin, pairing: 'Jus de pomme artisanal' },
  { name: 'Roasted Duck à l’Orange', category: 'Dinner', description: 'Classic French-style duck with orange reduction and seasonal vegetables.', ingredients: 'Duck · Blood orange · Carrot · Thyme', calories: '610 kcal', image: images.dining, pairing: 'Côtes-du-Rhône 2021' },
  { name: 'Chocolate Soufflé', category: 'Desserts', description: 'Warm dark chocolate soufflé with vanilla crème anglaise.', ingredients: 'Dark chocolate · Madagascar vanilla · Egg', calories: '390 kcal', image: images.dining, pairing: 'Cognac XO' },
];

function Emblem({ small = false }: { small?: boolean }) {
  return <div className={`emblem ${small ? 'emblem-small' : ''}`}><Shield size={small ? 18 : 28} strokeWidth={1.4} /><span className="emblem-mark">G</span></div>;
}

function App() {
  const [page, setPage] = useState<Page>('home');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [bookingStep, setBookingStep] = useState<BookingStep>('search');
  const [selectedFlight, setSelectedFlight] = useState(flights[0]);
  const [selectedSeat, setSelectedSeat] = useState('2A');
  const [selectedMeal, setSelectedMeal] = useState(meals[0]);
  const [confirmed, setConfirmed] = useState(false);

  const go = (next: Page) => { setPage(next); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const startBooking = () => { setPage('booking'); setBookingStep('search'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const bookingProgress = ['search', 'results', 'seat', 'dining', 'passenger', 'review'];

  return <div className="app-shell">
    <header className="topbar">
      <button className="brand" onClick={() => go('home')} aria-label="Guardian Airline home"><Emblem small /><span>GUARDIAN <b>AIRLINE</b></span></button>
      <nav className={mobileOpen ? 'main-nav open' : 'main-nav'}>
        <button onClick={() => go('home')}>Home</button>
        {navItems.map(item => <button key={item.page} onClick={() => go(item.page)}>{item.label}</button>)}
        <div className="nav-utility"><button onClick={() => go('manage')}>Manage booking</button><button onClick={() => go('checkin')}>Check-in</button><button onClick={() => go('status')}>Flight status</button></div>
        <button className="nav-book" onClick={startBooking}>Book a flight <ArrowRight size={14} /></button>
      </nav>
      <button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open menu">{mobileOpen ? <X /> : <Menu />}</button>
    </header>

    {page === 'home' && <Home go={go} startBooking={startBooking} />}
    {page === 'about' && <About />}
    {page === 'services' && <Services startBooking={startBooking} />}
    {page === 'fleet' && <Fleet />}
    {page === 'destinations' && <Destinations startBooking={startBooking} />}
    {page === 'dining' && <Dining />}
    {page === 'concierge' && <Concierge go={go} />}
    {page === 'contact' && <Contact />}
    {page === 'booking' && <Booking step={bookingStep} setStep={setBookingStep} selectedFlight={selectedFlight} setSelectedFlight={setSelectedFlight} selectedSeat={selectedSeat} setSelectedSeat={setSelectedSeat} selectedMeal={selectedMeal} setSelectedMeal={setSelectedMeal} confirmed={confirmed} setConfirmed={setConfirmed} progress={bookingProgress} />}
    {page === 'manage' && <UtilityPage type="manage" />}
    {page === 'checkin' && <UtilityPage type="checkin" />}
    {page === 'status' && <UtilityPage type="status" />}
    <Footer go={go} />
  </div>;
}

function Home({ go, startBooking }: { go: (page: Page) => void; startBooking: () => void }) {
  return <main>
    <section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(9,10,10,.78), rgba(9,10,10,.24)), url(${heroImage})` }}>
      <div className="hero-copy reveal"><p className="eyebrow">PARIS · FRANCE / EST. 2026</p><h1>Absolute security.<br /><i>Exceptional journey.</i></h1><p className="hero-sub">Premium aviation designed for those who value time, privacy, and peace of mind.</p><div className="button-row"><button className="gold-button" onClick={startBooking}>Book a flight <ArrowRight size={16} /></button><button className="text-button" onClick={() => go('about')}>Discover Guardian <ArrowRight size={16} /></button></div></div>
      <div className="hero-foot"><span>01 — 03</span><span>Private aviation, redefined</span><span className="hero-line" /></div>
    </section>
    <section className="section standard"><div className="section-intro"><p className="eyebrow">THE GUARDIAN STANDARD</p><h2>Where discretion becomes<br /><i>an art form.</i></h2><p>Based in the heart of France, Guardian Airline redefines premium aviation by merging impenetrable security with bespoke elegance.</p></div><div className="pillar-grid">{[['01','Absolute security','Advanced protection designed around every stage of the journey.',Shield],['02','Complete discretion','Private, seamless travel designed to protect your privacy.',LockKeyhole],['03','Bespoke luxury','Exceptional comfort, cuisine, and service tailored to every passenger.',Sparkles]].map(([n,title,text,Icon]) => <div className="pillar" key={title as string}><span className="number">{n as string}</span><Icon size={22} strokeWidth={1.2} /><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></section>
    <section className="split-feature"><div className="image-panel" style={{ backgroundImage: `url(${images.architecture})` }} /><div className="dark-panel"><p className="eyebrow">THE GRIFFIN'S PROMISE</p><h2>Protection for what<br /><i>matters most.</i></h2><p>In ancient mythology, the majestic Griffin was the fierce protector of the world’s most priceless treasures. For Guardian, it is more than a symbol; it is a vow.</p><button className="text-button" onClick={() => go('about')}>Read our story <ArrowRight size={16} /></button><div className="large-emblem"><Emblem /></div></div></section>
    <section className="quote-section"><p className="eyebrow">THE GUARDIAN DIFFERENCE</p><blockquote>“The luxury of arriving<br /><i>entirely unhurried.</i>”</blockquote><div className="quote-rule" /></section>
    <section className="feature-row"><div><p className="eyebrow">BESPOKE FRENCH GASTRONOMY</p><h2>The table is set<br /><i>at 40,000 feet.</i></h2><p>Menus conceived by the great houses of France, served with the quiet confidence of a private dining room.</p><button className="outline-button" onClick={() => go('dining')}>Explore dining <ArrowRight size={16} /></button></div><div className="feature-image" style={{ backgroundImage: `url(${images.dining})` }} /></section>
  </main>;
}

function PageHero({ eyebrow, title, text, image }: { eyebrow: string; title: React.ReactNode; text?: string; image?: string }) { return <section className="page-hero" style={image ? { backgroundImage: `linear-gradient(90deg, rgba(9,10,10,.78), rgba(9,10,10,.18)), url(${image})` } : undefined}><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text && <p className="lead">{text}</p>}</div></section>; }
function About() { return <main><PageHero eyebrow="THE HOUSE OF GUARDIAN" title={<>About Guardian<br /><i>Airline.</i></>} text="A sanctuary in the sky for those who expect more from the journey." image={images.architecture} /><section className="editorial"><div className="editorial-sticky"><p className="eyebrow">OUR PURPOSE</p><span className="gold-rule" /></div><div><h2>Travel without<br /><i>compromise.</i></h2><p>Based in the heart of France, Guardian Airline redefines premium aviation by merging impenetrable security with bespoke elegance. We understand that for global leaders, executives, and discerning travelers, time and safety are the ultimate luxuries.</p><p>Our mission is to provide an absolute sanctuary in the sky. From state-of-the-art aircraft equipped with classified-grade cyber and physical defense systems to our meticulously vetted, elite-trained crew, every detail is engineered for your absolute peace of mind.</p><div className="signature">GUARDIAN AIRLINE <span>PARIS</span></div></div></section><section className="promise"><Emblem /><div><p className="eyebrow">THE GRIFFIN'S PROMISE</p><h2>Our most precious<br /><i>cargo is you.</i></h2><p>Rendered in brilliant gold against our sleek, minimalist livery, the Guardian Griffin symbolizes our aerial dominance, our ground-level vigilance, and our unwavering commitment to guarding every passenger.</p></div></section></main>; }
function Services({ startBooking }: { startBooking: () => void }) { const cards = [['01','Discreet terminal access','Bypass crowded public airports entirely with private, VIP-only boarding protocols.',Globe2],['02','Encrypted connectivity','Conduct highly sensitive business using fully encrypted in-flight Wi-Fi networks.',LockKeyhole],['03','Elite protection','Hospitality experts cross-trained in advanced emergency response and executive protection.',Shield],['04','Bespoke French gastronomy','World-class culinary experiences curated by top chefs from our French headquarters.',Utensils]]; return <main><PageHero eyebrow="THE GUARDIAN STANDARD" title={<>Services<br /><i>without equal.</i></>} text="Every detail is engineered around your freedom to focus on what matters." image={images.cabin} /><section className="service-grid">{cards.map(([n,title,text,Icon]) => <article className="service-card" key={title as string}><span className="number">{n as string}</span><Icon size={27} strokeWidth={1.1} /><h2>{title as string}</h2><p>{text as string}</p><ArrowRight className="card-arrow" size={18} /></article>)}</section><section className="center-cta"><p className="eyebrow">THE PRIVATE DIFFERENCE</p><h2>Your time, returned<br /><i>to you.</i></h2><button className="gold-button" onClick={startBooking}>Book your journey <ArrowRight size={16} /></button></section></main>; }
function Fleet() { const fleet = [['Guardian G1','Ultra-long-range executive aircraft','13,500 km','14 guests','Private suites','Always available',heroImage],['Guardian G2','Long-range luxury aircraft','9,800 km','18 guests','Club configuration','Always available',images.cabin],['Guardian G3','Premium regional aircraft','5,200 km','28 guests','2 × 1 leather seats','Always available',images.architecture]]; return <main><PageHero eyebrow="THE GUARDIAN FLEET" title={<>Made to go<br /><i>further.</i></>} text="Three aircraft. One uncompromising standard." /><section className="fleet-list">{fleet.map((jet,index) => <article className="fleet-card" key={jet[0]}><div className="fleet-photo" style={{ backgroundImage: `url(${jet[6]})` }}><span>0{index+1}</span></div><div className="fleet-info"><p className="eyebrow">{jet[1]}</p><h2>{jet[0]}</h2><div className="spec-grid"><span><b>Range</b>{jet[2]}</span><span><b>Capacity</b>{jet[3]}</span><span><b>Cabin</b>{jet[4]}</span><span><b>Connectivity</b>{jet[5]}</span></div><button className="text-button">Explore aircraft <ArrowRight size={16} /></button></div></article>)}</section></main>; }
function Destinations({ startBooking }: { startBooking: () => void }) { const cities = [['Paris','France','LBG · Le Bourget','—','From €980',images.paris],['London','United Kingdom','FAB · Farnborough','01h 10m','From €1,240',images.london],['Tokyo','Japan','HND · Haneda','12h 45m','From €4,850',images.tokyo],['Dubai','United Arab Emirates','DWC · Al Maktoum','06h 40m','From €2,890',images.dubai],['New York','United States','TEB · Teterboro','08h 05m','From €3,600',heroImage],['Geneva','Switzerland','GVA · Geneva','01h 05m','From €890',images.architecture]]; return <main><PageHero eyebrow="THE GUARDIAN NETWORK" title={<>The world,<br /><i>discreetly.</i></>} text="Direct access to the places that move the world." /><section className="destination-grid">{cities.map(city => <article className="destination-card" key={city[0]} style={{ backgroundImage: `linear-gradient(0deg, rgba(0,0,0,.85), transparent 70%), url(${city[5]})` }}><div className="destination-copy"><p className="eyebrow">{city[1]}</p><h2>{city[0]}</h2><span>{city[2]}</span><div><small>{city[3]}</small><small>{city[4]}</small></div></div></article>)}</section><div className="center-cta"><button className="gold-button" onClick={startBooking}>Plan your journey <ArrowRight size={16} /></button></div></main>; }
function Dining() { const [category, setCategory] = useState('All'); const filtered = category === 'All' ? meals : meals.filter(meal => meal.category === category); return <main><PageHero eyebrow="THE GUARDIAN TABLE" title={<>French gastronomy<br /><i>at 40,000 feet.</i></>} text="A dining experience designed with the intimacy of a private restaurant." image={images.dining} /><section className="dining-menu"><div className="category-bar">{['All','Breakfast','Dinner','Desserts','Vegetarian'].map(item => <button className={category === item ? 'active' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="meal-grid">{filtered.map(meal => <article className="meal-card" key={meal.name}><div className="meal-image" style={{ backgroundImage: `url(${meal.image})` }} /><div className="meal-content"><p className="eyebrow">{meal.category}</p><h2>{meal.name}</h2><p>{meal.description}</p><span className="ingredients">{meal.ingredients}</span><div className="meal-meta"><span>{meal.calories}</span><span>Pairing · {meal.pairing}</span></div></div></article>)}</div></section></main>; }
function Concierge({ go }: { go: (page: Page) => void }) { return <main><PageHero eyebrow="A QUIETLY PERSONAL SERVICE" title={<>Guardian<br /><i>Concierge.</i></>} text="Your journey begins long before you reach the aircraft." image={images.architecture} /><section className="concierge-layout"><div><p className="eyebrow">AT YOUR SERVICE</p><h2>Consider it<br /><i>handled.</i></h2><p>From a discreet car waiting at the curb to a hotel suite prepared exactly as you like it, our Concierge team orchestrates the details that make a journey feel effortless.</p><button className="gold-button" onClick={() => go('contact')}>Contact concierge <ArrowRight size={16} /></button></div><div className="concierge-list">{['Private airport transfers','Executive travel assistance','VIP terminal access','Hotel coordination','Ground transportation','Corporate travel planning','Special requests'].map((item, i) => <div key={item}><span>0{i+1}</span>{item}<ArrowRight size={16} /></div>)}</div></section></main>; }
function Contact() { return <main><PageHero eyebrow="A DIRECT LINE" title={<>Executive<br /><i>support.</i></>} text="For those who prefer a conversation, our team is ready." /><section className="contact-layout"><div><p className="eyebrow">GET IN TOUCH</p><h2>How may we<br /><i>assist?</i></h2><div className="contact-options"><span><b>Guardian Concierge</b> concierge@guardian-airline.fr</span><span><b>Booking Assistance</b> +33 (0)1 84 80 20 26</span><span><b>Executive Travel Support</b> Available 24 hours</span></div></div><form className="contact-form" onSubmit={e => e.preventDefault()}><label>Your name<input placeholder="Full name" /></label><label>Email address<input type="email" placeholder="name@company.com" /></label><label>How can we help?<select><option>Choose a subject</option><option>Guardian Concierge</option><option>Booking assistance</option><option>Corporate travel</option></select></label><label>Your message<textarea placeholder="Tell us how we may assist..." rows={4} /></label><button className="gold-button">Send enquiry <ArrowRight size={16} /></button></form></section></main>; }

function Booking({ step, setStep, selectedFlight, setSelectedFlight, selectedSeat, setSelectedSeat, selectedMeal, setSelectedMeal, confirmed, setConfirmed, progress }: { step: BookingStep; setStep: (s: BookingStep) => void; selectedFlight: typeof flights[0]; setSelectedFlight: (f: typeof flights[0]) => void; selectedSeat: string; setSelectedSeat: (s: string) => void; selectedMeal: typeof meals[0]; setSelectedMeal: (m: typeof meals[0]) => void; confirmed: boolean; setConfirmed: (v: boolean) => void; progress: string[] }) {
  const [searching, setSearching] = useState(false); const [passenger, setPassenger] = useState('John Doe');
  const next = (s: BookingStep) => setStep(s);
  const runSearch = () => { setSearching(true); window.setTimeout(() => { setSearching(false); next('results'); }, 650); };
  if (confirmed) return <main><section className="confirmation"><div className="confirmation-mark"><Check size={42} /></div><p className="eyebrow">GA7X92K · BOOKING CONFIRMED</p><h1>Your journey is<br /><i>secured.</i></h1><p className="lead">Your private sanctuary in the sky awaits.</p><div className="boarding-pass"><div><Emblem /><span className="pass-type">GUARDIAN / FIRST</span></div><div className="pass-route"><span>CDG</span><ArrowRight /><span>HND</span></div><div className="pass-data"><span><b>Passenger</b>{passenger}</span><span><b>Flight</b>{selectedFlight.number}</span><span><b>Date</b>15 Oct 2026</span><span><b>Seat</b>{selectedSeat}</span><span><b>Departure</b>{selectedFlight.depart}</span><span><b>Meal</b>{selectedMeal.name}</span></div><div className="barcode">|||| ||| |||| || ||| ||||</div></div><div className="button-row center"><button className="gold-button"><Download size={15} /> Download itinerary</button><button className="outline-button" onClick={() => { setConfirmed(false); next('search'); }}>New booking</button></div></section></main>;
  return <main className="booking-page"><div className="booking-heading"><p className="eyebrow">PRIVATE RESERVATIONS</p><h1>Book a <i>flight.</i></h1><div className="progress">{progress.map((item, i) => <span className={progress.indexOf(step) >= i ? 'done' : ''} key={item}><b>0{i+1}</b>{item}</span>)}</div></div>
    {step === 'search' && <section className="booking-card search-card"><div className="booking-card-head"><div><p className="eyebrow">01 / SEARCH FLIGHT</p><h2>Where will we take you?</h2></div><Plane size={30} strokeWidth={1} /></div><div className="search-grid"><label>From<select><option>Paris · CDG</option><option>London · FAB</option><option>Geneva · GVA</option></select></label><label>To<select><option>Tokyo · HND</option><option>New York · TEB</option><option>Dubai · DWC</option></select></label><label>Departure<input type="date" defaultValue="2026-10-15" /></label><label>Return<input type="date" defaultValue="2026-10-22" /></label><label>Passengers<select><option>1 passenger</option><option>2 passengers</option><option>3 passengers</option></select></label><label>Cabin class<select><option>Guardian First</option><option>Guardian Business</option><option>Guardian Private Suite</option></select></label></div><button className="gold-button" onClick={runSearch}>{searching ? 'Searching...' : 'Search flights'} <ArrowRight size={16} /></button></section>}
    {step === 'results' && <section className="booking-card"><div className="booking-card-head"><div><p className="eyebrow">02 / AVAILABLE FLIGHTS</p><h2>Paris <i>to</i> Tokyo</h2><p className="muted">15 October 2026 · Guardian First · 1 passenger</p></div><button className="back-button" onClick={() => next('search')}><ChevronLeft size={15} /> Edit search</button></div><div className="flight-results">{flights.map(flight => <div className={selectedFlight.number === flight.number ? 'flight-result selected' : 'flight-result'} key={flight.number}><span className="flight-number">{flight.number}<small>{flight.aircraft}</small></span><span><b>{flight.depart}</b><small>Paris · CDG</small></span><span className="flight-duration"><small>{flight.duration}</small><i /><small>{flight.stops}</small></span><span><b>{flight.arrive}</b><small>Tokyo · HND</small></span><span className="flight-price"><small>Starting from</small><b>{flight.price}</b></span><button className="select-button" onClick={() => { setSelectedFlight(flight); next('seat'); }}>{selectedFlight.number === flight.number ? 'Selected' : 'Select flight'}</button></div>)}</div></section>}
    {step === 'seat' && <section className="booking-card"><div className="booking-card-head"><div><p className="eyebrow">03 / YOUR SEAT</p><h2>Choose your <i>sanctuary.</i></h2><p className="muted">{selectedFlight.number} · Guardian First · Airbus-inspired cabin</p></div></div><div className="seat-layout"><div className="seat-map"><div className="cockpit">COCKPIT</div>{['1A','1C','1D','1F','2A','2C','2D','2F','3A','3C','3D','3F','4A','4C','4D','4F','5A','5C','5D','5F','6A','6C','6D','6F'].map((seat, i) => <button className={`${selectedSeat === seat ? 'chosen ' : ''}${i % 7 === 0 ? 'suite ' : i % 3 === 0 ? 'privacy ' : ''}${[1, 8, 14].includes(i) ? 'unavailable' : ''}`} disabled={[1, 8, 14].includes(i)} onClick={() => setSelectedSeat(seat)} key={seat}>{seat}</button>)}</div><div className="seat-legend"><p className="eyebrow">SELECTED SEAT</p><h3>{selectedSeat} <span>Privacy Window</span></h3><p>Extra privacy and increased personal space.</p><div className="legend"><span><i className="suite-dot" /> Suite · +€480</span><span><i className="privacy-dot" /> Privacy · +€180</span><span><i className="window-dot" /> Window · +€90</span></div><button className="gold-button" onClick={() => next('dining')}>Continue to dining <ArrowRight size={16} /></button></div></div></section>}
    {step === 'dining' && <section className="booking-card"><div className="booking-card-head"><div><p className="eyebrow">04 / IN-FLIGHT DINING</p><h2>Bespoke French <i>gastronomy.</i></h2><p className="muted">Choose your dining preference for the journey.</p></div><Utensils size={28} strokeWidth={1} /></div><div className="booking-meal-grid">{meals.slice(0,3).map(meal => <button className={selectedMeal.name === meal.name ? 'booking-meal selected' : 'booking-meal'} onClick={() => setSelectedMeal(meal)} key={meal.name}><div style={{ backgroundImage: `url(${meal.image})` }} /><span><p className="eyebrow">{meal.category}</p><b>{meal.name}</b><small>{meal.description}</small></span>{selectedMeal.name === meal.name && <Check size={16} />}</button>)}</div><button className="gold-button" onClick={() => next('passenger')}>Continue to passenger details <ArrowRight size={16} /></button></section>}
    {step === 'passenger' && <section className="booking-card"><div className="booking-card-head"><div><p className="eyebrow">05 / PASSENGER DETAILS</p><h2>Who is <i>travelling?</i></h2></div><UserRound size={28} strokeWidth={1} /></div><div className="passenger-grid"><label>First name<input defaultValue="John" /></label><label>Last name<input defaultValue="Doe" /></label><label>Date of birth<input type="date" defaultValue="1984-04-12" /></label><label>Nationality<select><option>French</option><option>British</option><option>American</option><option>Japanese</option></select></label><label>Passport number<input defaultValue="FR 48 203 991" /></label><label>Email<input type="email" defaultValue="john.doe@company.com" /></label><label>Phone number<input defaultValue="+33 6 20 40 80 10" /></label></div><p className="privacy-note"><LockKeyhole size={15} /> Your personal information is protected through Guardian Airline’s secure passenger data system.</p><button className="gold-button" onClick={() => { setPassenger('John Doe'); next('review'); }}>Continue to review <ArrowRight size={16} /></button></section>}
    {step === 'review' && <section className="booking-card review-card"><div className="booking-card-head"><div><p className="eyebrow">06 / FINAL REVIEW</p><h2>Your journey, <i>precisely.</i></h2></div><CircleHelp size={27} strokeWidth={1} /></div><div className="review-layout"><div className="review-details"><div><p className="eyebrow">FLIGHT</p><h3>Paris → Tokyo</h3><p>{selectedFlight.number} · {selectedFlight.depart} — {selectedFlight.arrive} · 15 October 2026</p></div><div><p className="eyebrow">CABIN</p><h3>Guardian First</h3><p>{selectedFlight.aircraft} · Non-stop</p></div><div><p className="eyebrow">PASSENGER</p><h3>{passenger}</h3><p>Passport verified</p></div><div><p className="eyebrow">SEAT & DINING</p><h3>{selectedSeat} · Privacy Window</h3><p>{selectedMeal.name}</p></div></div><div className="price-summary"><span>Base fare <b>€4,850</b></span><span>Seat selection <b>€180</b></span><span>Dining <b>Included</b></span><span>Taxes & fees <b>€410</b></span><hr /><span className="total">Total <b>€5,440</b></span><button className="gold-button" onClick={() => setConfirmed(true)}>Confirm booking <ArrowRight size={16} /></button></div></div></section>}
  </main>;
}

function UtilityPage({ type }: { type: 'manage' | 'checkin' | 'status' }) { const [submitted, setSubmitted] = useState(false); const labels = { manage: ['MANAGE YOUR JOURNEY', 'Retrieve your booking.', 'Booking reference', 'Passenger last name', 'Retrieve booking'], checkin: ['SECURE CHECK-IN', 'Your journey awaits.', 'Booking reference', 'Passenger last name', 'Begin secure check-in'], status: ['FLIGHT INFORMATION', 'Know before you go.', 'Flight number', 'Departure airport', 'Search flight status'] }; const current = labels[type]; return <main><PageHero eyebrow={current[0]} title={<>{current[1].split(' ')[0]} <i>{current[1].split(' ').slice(1).join(' ')}</i></>} text="Access your journey details through our discreet passenger portal." /><section className="utility-layout"><div className="utility-form"><p className="eyebrow">{current[0]}</p><h2>Enter your<br /><i>details.</i></h2><label>{current[2]}<input placeholder={type === 'status' ? 'GA 001' : 'GA7X92K'} /></label><label>{current[3]}<input placeholder={type === 'status' ? 'Paris · CDG' : 'Doe'} /></label><button className="gold-button" onClick={() => setSubmitted(true)}>{current[4]} <ArrowRight size={16} /></button></div><div className="utility-aside"><Shield size={30} strokeWidth={1} /><p className="eyebrow">GUARDIAN PROTOCOL</p><h3>Your privacy is<br /><i>always protected.</i></h3><p>Information is handled with the same precision and discretion as every Guardian journey.</p></div></section>{submitted && <section className="utility-result"><Check size={20} /><div><p className="eyebrow">{type === 'checkin' ? 'CHECK-IN COMPLETE' : type === 'status' ? 'GA 001 · ON TIME' : 'BOOKING LOCATED'}</p><h2>{type === 'checkin' ? 'You are ready to travel.' : type === 'status' ? 'Boarding begins at 09:55.' : 'Welcome back, John Doe.'}</h2><p>{type === 'checkin' ? 'Seat 2A · Boarding 09:55 · Gate A12' : type === 'status' ? 'Paris CDG · Terminal 2E · Guardian G1' : 'Paris → Tokyo · 15 October 2026 · Guardian First'}</p></div></section>}</main>; }
function Footer({ go }: { go: (page: Page) => void }) { return <footer><div className="footer-top"><div><button className="brand footer-brand" onClick={() => go('home')}><Emblem small /><span>GUARDIAN <b>AIRLINE</b></span></button><p>Absolute security.<br /><i>Exceptional journey.</i></p></div><div className="footer-columns"><div><b>Explore</b><button onClick={() => go('about')}>About Guardian</button><button onClick={() => go('services')}>Services</button><button onClick={() => go('fleet')}>Fleet</button><button onClick={() => go('destinations')}>Destinations</button></div><div><b>Travel</b><button onClick={() => go('manage')}>Manage booking</button><button onClick={() => go('checkin')}>Check-in</button><button onClick={() => go('status')}>Flight status</button><button onClick={() => go('concierge')}>Guardian Concierge</button></div><div><b>Connect</b><button onClick={() => go('contact')}>Contact</button><button>Careers</button><button>Privacy</button><button>Terms</button></div></div></div><div className="footer-bottom"><span>© 2026 Guardian Airline · Paris, France</span><span>Instagram · LinkedIn · X</span></div></footer>; }

export default App;
